### ISSUE TITLE
gnuplot RuntimeError on OS X

### ISSUE THREAD

**Issue by georgedorn** [nuxeo/FunkLoad#139]
```
$ fl-build-report --html -o report/ simple-bench.xml
Creating html report: ...Traceback (most recent call last):
  File "/Users/user/workspace/loadtests.virt/bin/fl-build-report", line 9, in <module>
    load_entry_point('funkload==1.17.0', 'console_scripts', 'fl-build-report')()
  File "/Users/user/workspace/loadtests/.virt/lib/python2.7/site-packages/funkload/ReportBuilder.py", line 304, in main
    css_file=options.css_file)()
  File "/Users/user/workspace/loadtests/.virt/lib/python2.7/site-packages/funkload/ReportRenderHtmlBase.py", line 138, in render
    self.createCharts()
  File "/Users/user/workspace/loadtests/.virt/lib/python2.7/site-packages/funkload/ReportRenderHtmlBase.py", line 149, in createCharts
    self.createAllResponseChart()
  File "/Users/user/workspace/loadtests/.virt/lib/python2.7/site-packages/funkload/ReportRenderHtmlGnuPlot.py", line 415, in createAllResponseChart
    self.createRPSTimeChart()
  File "/Users/user/workspace/loadtests/.virt/lib/python2.7/site-packages/funkload/ReportRenderHtmlGnuPlot.py", line 410, in createRPSTimeChart
    gnuplot(plot_path)
  File "/Users/user/workspace/loadtests/.virt/lib/python2.7/site-packages/funkload/ReportRenderHtmlGnuPlot.py", line 52, in gnuplot
    "\n" + str(output))
RuntimeError: Failed to run gnuplot cmd: cd "/Users/user/workspace/loadtests/report/test_table-20150211T111834"; gnuplot "/Users/user/workspace/loadtests/report/test_table-20150211T111834/time_rps.gplot"

plot
     ^
"/Users/user/workspace/loadtests/report/test_table-20150211T111834/time_rps.gplot", line 11: function to plot expected
```

gnuplot 5.0 patchlevel 0 is installed via homebrew on OS X Yosemite.

**Comment by bdelbosc** [comment]
sed '11q;d' /Users/user/workspace/loadtests/report/test_table-20150211T111834/time_rps.gplot

**Comment by georgedorn** [comment]
Nevermind, this turned out to be a bad test run.

It'd be nice to have better messaging around that, but it's working now.
