### ISSUE TITLE
Fail to install from Git and .tar.gz: AttributeError: 'tuple' object has no attribute 'is_prerelease'

### ISSUE THREAD

**Issue by madarche** [nuxeo/FunkLoad#142]
AttributeError: 'tuple' object has no attribute 'is_prerelease'

**Comment by madarche** [comment]
Here are the steps to reproduce:

    sweet@joshua:~/funkload-1.17.0b-20140310$ python bootstrap.py
    Creating directory '/home/sweet/funkload-1.17.0b-20140310/bin'.
    Creating directory '/home/sweet/funkload-1.17.0b-20140310/parts'.
    Creating directory '/home/sweet/funkload-1.17.0b-20140310/eggs'.
    Creating directory '/home/sweet/funkload-1.17.0b-20140310/develop-eggs'.
    Generated script '/home/sweet/funkload-1.17.0b-20140310/bin/buildout'.
    sweet@joshua:~/funkload-1.17.0b-20140310$ bin/buildout
    While:
      Installing.
      Checking for upgrades.
      Getting distribution for 'zc.buildout>=2.3.1'.

    An internal error occurred due to a bug in either zc.buildout or in a
    recipe being used:
    Traceback (most recent call last):
      File "/home/sweet/funkload-1.17.0b-20140310/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 1946, in main
        getattr(buildout, command)(args)
      File "/home/sweet/funkload-1.17.0b-20140310/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 475, in install
        self._maybe_upgrade()
      File "/home/sweet/funkload-1.17.0b-20140310/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 910, in _maybe_upgrade
        allow_hosts = self._allow_hosts
      File "/home/sweet/funkload-1.17.0b-20140310/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 848, in install
        return installer.install(specs, working_set)
      File "/home/sweet/funkload-1.17.0b-20140310/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 635, in install
        for_buildout_run=for_buildout_run):
      File "/home/sweet/funkload-1.17.0b-20140310/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 477, in _get_dist
        dist, avail = self._satisfied(requirement)
      File "/home/sweet/funkload-1.17.0b-20140310/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 253, in _satisfied
        if _final_version(dist.parsed_version)
      File "/home/sweet/funkload-1.17.0b-20140310/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 1408, in _final_version
        return not parsed_version.is_prerelease
    AttributeError: 'tuple' object has no attribute 'is_prerelease'
