### ISSUE TITLE
pip install funkload==1.17.1 fails

### ISSUE THREAD

**Issue by iurisilvio** [nuxeo/FunkLoad#145]
I tried older versions and it works fine. Current master branch works too. The current (1.17.1) PyPI package fails.

Looks like README.txt was not packaged.

```
$ pip install funkload
Collecting funkload
  Using cached funkload-1.17.1.tar.gz
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.14.tar.gz
    Extracting in /tmp/tmp6iObvk
    Now working in /tmp/tmp6iObvk/distribute-0.6.14
    Building a Distribute egg in /tmp/pip-build-V0_ePc/funkload
    /tmp/pip-build-V0_ePc/funkload/distribute-0.6.14-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-V0_ePc/funkload/setup.py", line 33, in <module>
        long_description=''.join(open('README.txt').readlines()),
    IOError: [Errno 2] No such file or directory: 'README.txt'
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-V0_ePc/funkload
```

**Comment by nqn** [comment]
+1

**Comment by tsauerwein** [comment]
I am getting: `ImportError: No module named ez_setup` (Python 2.7.6)

    $ venv/bin/pip install funkload
    Downloading/unpacking funkload
      Downloading funkload-1.17.1.tar.gz (107kB): 107kB downloaded
      Running setup.py (path:/home/.../funkload/venv/build/funkload/setup.py) egg_info for package funkload
        Traceback (most recent call last):
          File "<string>", line 17, in <module>
          File "/home/.../funkload/venv/build/funkload/setup.py", line 24, in <module>
            import ez_setup
        ImportError: No module named ez_setup
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):

      File "<string>", line 17, in <module>

      File "/home/.../funkload/venv/build/funkload/setup.py", line 24, in <module>

        import ez_setup

    ImportError: No module named ez_setup

**Comment by iurisilvio** [comment]
@tsauerwein You have to `pip install ez_setup` to fix this error and get the same error I reported.

**Comment by tsauerwein** [comment]
@iurisilvio Actually FunkLoad contains the file [ez_setup.py](https://github.com/nuxeo/FunkLoad/blob/master/ez_setup.py), so there should be no need to install it manually. Maybe it's not included in the build? Because `venv/bin/pip install git+https://github.com/nuxeo/FunkLoad.git` worked without manually installing `ez_setup`.

**Comment by martianedd** [comment]
I am having the same problem. I suppose 1.16.1 is the way to go for now.

**Comment by oneself** [comment]
Still a problem.

**Comment by jerri** [comment]
Is funkload dead? Would be a pity...

**Comment by etel** [comment]
easy_install -U funkload works for me, pip seems to be broken.

**Comment by jaseywang** [comment]
agree with @etel, easy_install works fine, pip not.

**Comment by saaj** [comment]
In the latest archive (https://pypi.python.org/packages/source/f/funkload/funkload-1.17.1.tar.gz#md5=1bf832246a5bedbc7fbbf352841c8c0b) there's no file `ez_setup.py`. Though it's not compatible with Python3 anyway. Master is compatible. `pip install git+https://github.com/nuxeo/FunkLoad.git` works. Haven't checked yet whether it's functional, because there were Python3 `SyntaxError`s from webunit. Installation has succeed though.

**Comment by Souljourner8** [comment]
The easy_install method worked for me as @etel mentioned. pip still doesn't work to install funkload

**Comment by tokibito** [comment]
+1

**Comment by piotr-dobrogost** [comment]
The funny thing is version 1.17.1 was meant *to fix packaging issue on pypi* https://github.com/nuxeo/FunkLoad/releases/tag/1.17.1
