### ISSUE TITLE
Time data doesn't match. Need another format

### ISSUE THREAD

**Issue by 4el** [nuxeo/FunkLoad#151]
test_simple: Starting -----------------------------------
	Access our Demo app
test_simple: GET: http://beta.yagla.ru
	Page 1: Get url ...
test_simple:  Done in 0.144s
test_simple:  Load css and images...

Failure
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\funkload-1.17.1-py2.7.egg\funkload\FunkLoadTestCase.py", line 1019, in __call__
    testMethod()
  File "C:\Python27\Tests\test_simple.py", line 11, in test_simple
    res = self.get(server_url, description = 'Get url')
  File "C:\Python27\lib\site-packages\funkload-1.17.1-py2.7.egg\funkload\FunkLoadTestCase.py", line 434, in get
    follow_redirect=follow_redirect)
  File "C:\Python27\lib\site-packages\funkload-1.17.1-py2.7.egg\funkload\FunkLoadTestCase.py", line 367, in _browse
    self._browser.pageImages(url, page, self)
  File "C:\Python27\lib\site-packages\funkload-1.17.1-py2.7.egg\funkload\PatchWebunit.py", line 243, in WTC_pageImages
    sucker.feed(page)
  File "C:\Python27\lib\sgmllib.py", line 104, in feed
    self.goahead(0)
  File "C:\Python27\lib\sgmllib.py", line 138, in goahead
    k = self.parse_starttag(i)
  File "C:\Python27\lib\sgmllib.py", line 296, in parse_starttag
    self.finish_starttag(tag, attrs)
  File "C:\Python27\lib\sgmllib.py", line 341, in finish_starttag
    self.handle_starttag(tag, method, attrs)
  File "C:\Python27\lib\site-packages\webunit-1.3.10-py2.7.egg\webunit\IMGSucker.py", line 46, in handle_starttag
    method(attributes)
  File "C:\Python27\lib\site-packages\funkload-1.17.1-py2.7.egg\funkload\PatchWebunit.py", line 121, in do_img
    self.session.images[url] = self.session.fetch(url)
  File "C:\Python27\lib\site-packages\funkload-1.17.1-py2.7.egg\funkload\PatchWebunit.py", line 502, in WF_fetch
    decodeCookies(url, server, headers, self.cookies)
  File "C:\Python27\lib\site-packages\funkload-1.17.1-py2.7.egg\funkload\PatchWebunit.py", line 226, in decodeCookies
    expire = datetime.datetime.strptime(cookie['expires'],"%a, %d-%b-%Y %H:%M:%S %Z")
  File "C:\Python27\lib\_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data 'Wed, 07-Dec-16 06:06:40 GMT' does not match format '%a, %d-%b-%Y %H:%M:%S %Z'

**Comment by jchan1237** [comment]
I experience the same issue, what is the solution to resolve this issue?

**Comment by bdelbosc** [comment]
Hi, it looks like that the server does not follow the RFC recommendation and uses a date with 2 digits year instead of 4 no ?
